--1 LIST EMPLOYEE NUMBER, LAST NAME, FIRST NAME, SEX, AND SALARY OF EACH EMPLOYEE
SELECT 
	EMPLOYEE.EMP_NO,
	EMPLOYEE.LAST_NAME,
	EMPLOYEE.FIRST_NAME,
	EMPLOYEE.SEX,
	SALARIES.SALARY
FROM EMPLOYEE
INNER JOIN SALARIES ON (EMPLOYEE.EMP_NO = SALARIES.EMP_NO);

--2 LIST FIRST NAME, LAST NAME, AND HIRE DATE FOR EMPLOYEES HIRED IN 1986
SELECT
	EMPLOYEE.LAST_NAME,
	EMPLOYEE.FIRST_NAME,
	EMPLOYEE.HIRE_DATE
FROM EMPLOYEE
WHERE HIRE_DATE LIKE '%86'; 

--3 LIST THE MANAGER OF EACH DEPARTMENT ALONG WITH THEIR DEPARTMENT NUMBER, DEPARTMENT NAME, EMPLOYEE NUMBER, LAST NAME, AND FIRST NAME
SELECT
	DEPT_MANAGER.EMP_NO,
	DEPARTMENTS.DEPT_NO,
	DEPARTMENTS.DEPT_NAME,
	EMPLOYEE.LAST_NAME,
	EMPLOYEE.FIRST_NAME
FROM DEPT_MANAGER
INNER JOIN DEPARTMENTS ON (DEPT_MANAGER.DEPT_NO = DEPARTMENTS.DEPT_NO)
INNER JOIN EMPLOYEE ON (DEPT_MANAGER.EMP_NO = EMPLOYEE.EMP_NO);

--4 LIST THE DEPARTMENT NUMBER FOR EACH EMPLOYEE ALONG WITH THAT EMPLOYEE'S EMPLOYEE NUMBER, LAST NAME, FIRST NAME, AND DEPTARMENT NAME
SELECT
	EMPLOYEE.EMP_NO,
	EMPLOYEE.LAST_NAME,
	EMPLOYEE.FIRST_NAME,
	DEPT_EMP.DEPT_NO,
	DEPARTMENTS.DEPT_NAME
FROM EMPLOYEE
INNER JOIN DEPT_EMP ON (EMPLOYEE.EMP_NO = DEPT_EMP.EMP_NO)
INNER JOIN DEPARTMENTS ON (DEPT_EMP.DEPT_NO = DEPARTMENTS.DEPT_NO);

--5 LIST FIRST NAME, LAST NAME, AND SEX OF EACH EMPLOYEE WHOSE FIRST NAME IS HERCULES AND WHOSE LAST NAME BEGINS WITH THE LETTER 'B'
SELECT
	EMPLOYEE.FIRST_NAME,
	EMPLOYEE.LAST_NAME,
	EMPLOYEE.SEX
FROM EMPLOYEE
WHERE FIRST_NAME = 'Hercules' AND LAST_NAME LIKE 'B%';

--6 LIST EACH EMPLOYEE IN THE SALES DEPARTMENT INCLUDING THEIR EMPLOYEE NUMBER, LAST NAME, AND FIRST NAME
SELECT
	EMPLOYEE.EMP_NO,
	EMPLOYEE.LAST_NAME,
	EMPLOYEE.FIRST_NAME,
	DEPT_EMP.DEPT_NO,
	DEPARTMENTS.DEPT_NAME
FROM EMPLOYEE
INNER JOIN DEPT_EMP ON (EMPLOYEE.EMP_NO = DEPT_EMP.EMP_NO)
INNER JOIN DEPARTMENTS ON (DEPT_EMP.DEPT_NO = DEPARTMENTS.DEPT_NO)
WHERE DEPT_NAME = 'Sales';
	
--7 LIST EACH EMPLOYEE IN SALES AND DEVELOPMENT DEPARTMENTS, INCLUDING THEIR EMPLOYEE NUMBER, LAST NAME, FIRST NAME, AND DEPARTMENT NAME
SELECT
	EMPLOYEE.EMP_NO,
	EMPLOYEE.LAST_NAME,
	EMPLOYEE.FIRST_NAME,
	DEPT_EMP.DEPT_NO,
	DEPARTMENTS.DEPT_NAME
FROM EMPLOYEE
INNER JOIN DEPT_EMP ON (EMPLOYEE.EMP_NO = DEPT_EMP.EMP_NO)
INNER JOIN DEPARTMENTS ON (DEPT_EMP.DEPT_NO = DEPARTMENTS.DEPT_NO)
WHERE DEPT_NAME = 'Sales' OR DEPT_NAME = 'Development';

--8 LIST THE FREQUENCY COUNTS, IN DECENDING ORDER, OF ALL THE EMPLOYEE LAST NAMES (THAT IS, HOW MANY EMPLOYEES SHARE EACH LAST NAME)
SELECT
	EMPLOYEE.LAST_NAME,
	COUNT (EMPLOYEE.LAST_NAME) AS "LAST NAMES COUNT"
FROM EMPLOYEE
GROUP BY LAST_NAME
ORDER BY "LAST NAMES COUNT" DESC;
